<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\MessageController;
use Illuminate\Support\Facades\Route;

// Publicly accessible page (The Default Welcome Screen)
Route::get('/', function () {
    return view('welcome');
});

// Default Dashboard Route (Protected by authentication)
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Protected Routes Group: Users MUST be logged in to access these
Route::middleware('auth')->group(function () {
    // Laravel Breeze Default Profile Routes
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Private Messaging App Routes
    Route::get('/messages', [MessageController::class, 'index'])->name('messages.index');
    Route::post('/messages', [MessageController::class, 'store'])->name('messages.store');
});

// Load the default authentication routes generated by Breeze (login, register, logout)
require __DIR__.'/auth.php';